### ISSUE TITLE
ineffassign support

### ISSUE THREAD

**Issue by steenzout** [hailiang/goclean#3]
@h12w would you be interested in including [gordonklaus/ineffassign](https://github.com/gordonklaus/ineffassign)?

if so I can make a PR.

**Comment by h12w** [comment]
Sure, just add it.
It is a simple script, and it would be easy to comment out the features you do not want to include.

**Comment by steenzout** [comment]
I've got a branch ready but I need to fix https://github.com/gordonklaus/ineffassign/issues/12 first.
